scrapers:
  - name: LeReflet
    url: https://www.lereflet.ch/programme
    item: article
    fields:
      - name: "location"
        value: "Théâtre Le Reflet"
      - name: city
        value: Vevey
      - name: country
        value: Switzerland
      - name: "sourceUrl"
        value: https://www.lereflet.ch/programme
      - name: title
        type: text
        location:
          - selector: h2.section-title > a
      - name: url
        type: url
        location:
          - selector: a
            attr: href
      - name: type
        type: text
        location:
          attr: data-categories
        transform:
          - type: regex-replace
            regex: ".*(T|t)héâtre.*"
            replace: THEATRE
          - type: regex-replace
            regex: Humour
            replace: COMEDY
          - type: regex-replace
            regex: Cirque
            replace: PERFORMING_VISUAL_ARTS
          - type: regex-replace
            regex: Danse
            replace: PERFORMING_VISUAL_ARTS
      - name: imageUrl
        type: url
        location:
          - selector: picture > img
            attr: src
      - name: comment
        type: text
        on_subpage: url
        location:
          - selector: div.content
            entire_subtree: true
      - name: date
        type: date
        on_subpage: url
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: date
            layout:
              - "Mon. 2 January 2006"
          - covers:
              time: true
            location:
              selector: time
            layout:
              - "15:04"
        date_location: Europe/Zurich
        date_language: fr_FR

