#!/bin/sh

export PATH=${PATH}:${HOME}/go/bin

cd ${HOME}/mobilisons-ch-scrapers
#goskyr scrape -c config

BOT=${HOME}/go/bin/go-mobilizon-bot
OPTS="--actor=65691 --concertcloudurl=http://localhost:5000/api/events --authconfig=${HOME}/.config/mobilizon/auth.json"

${BOT} ${OPTS} --config=venues/polesud --city=Lausanne --group=153626 --location "Pôle Sud"
#${BOT} ${OPTS} --config=venues/datcha --city=Lausanne --group=1085719 --location "La Datcha"
#${BOT} ${OPTS} --config=venues/reflet --city=Vevey --group=1086824 --location "Le Reflet"
#${BOT} ${OPTS} --config=venues/passage --city=Neuchâtel --group=1065170 --location "Theatre du Passage"
